### ISSUE TITLE
Improve browser compatibility

### ISSUE THREAD

**Issue by pavelstudeny** [vweevers/hyperloglog32#1]
I'm using hyperloglog32 in a browser and here are a few suggestions, as the current version has a few weaknesses out of Node:
* Buffer does not exist in a browser, while Uint8Array is available everywhere
* murmur32 does not have murmurhash3 as an optional or peer dependency, so npm install fail if the build machine does not have a compiler. Except for a very performance-intense usage, there is no strong reason to use the native version. It's better to use murmurhash-js directly.
* In addition, constructor could have an optional parameter to directly initialize with a saved state.

[index.txt](https://github.com/vweevers/hyperloglog32/files/1932088/index.txt)

**Comment by vweevers** [comment]
> Buffer does not exist in a browser, while Uint8Array is available everywhere

Buffer support should be provided by a bundler like browserify.

> murmur32 does not have murmurhash3 as an optional or peer dependency

It's an optional dependency: https://github.com/vweevers/murmur32/blob/3d555db593d79faee674e5fb496def5e41bd61b7/package.json#L22-L24

> In addition, constructor could have an optional parameter to directly initialize with a saved state.

PR is welcome!

**Comment by pavelstudeny** [comment]
Apologies, I haven't noticed the optionality in the npm-installed package.json. If you don't like the Uint8Array idea, then the constructor parameter is too simple for a PR :-)
```
... function HyperLogLog(n, savedState)
...
  if (savedState) self.merge(savedState)

  return self;
```
